FROM openjdk:7
COPY . /Users/wirthjan/notes/lectures/progII
WORKDIR /Users/wirthjan/notes/lectures/progII
RUN javac BeautifiedJavaCode.java
RUN java BeautifiedJavaCode
RUN javac ImprovedBeautifiedJavaCode.java
RUN java ImprovedBeautifiedJavaCode 16 37
# CMD ["java", "ScrambledJavaCode"]
