FROM openjdk:7
COPY . /Users/wirthjan/notes/lectures/progII
WORKDIR /Users/wirthjan/notes/lectures/progII
# RUN javac MyDate.java
# RUN java -ea MyDate
RUN javac PersonTester.java
RUN java -ea PersonTester
