FROM openjdk:7
COPY . /Users/wirthjan/notes/lectures/progII
WORKDIR /Users/wirthjan/notes/lectures/progII
RUN javac AnagrammCheck.java
RUN java AnagrammCheck "Smithy Stank" "My Hat Stinks"
RUN java AnagrammCheck "notanangramlol " "hellno"
